services:
  # Backend API Server
  - type: web
    name: lms-backend
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    # Add your environment variables in Render dashboard:
    # MONGO_URI, CLIENT_ORIGIN, CLOUDINARY_*, JWT_SECRET

  # Frontend Static Site
  - type: static
    name: lms-frontend
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://your-backend-service-name.onrender.com
