services:
  - type: web
    name: frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist

  - type: web
    name: backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
